services:
  app:
    build: .
    container_name: referral-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
  
  db:
    container_name:  postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - 5432:5432